# apps/asrp-frontend/nginx.conf
#
# [FIX] NGINX unprivileged escucha en 8080.
# SPA routing + proxy /api -> api-gateway:4000 (evita CORS - Cross-Origin Resource Sharing)

server {
  listen 8080;
  server_name _;

  add_header X-Content-Type-Options nosniff always;
  add_header X-Frame-Options DENY always;
  add_header Referrer-Policy no-referrer always;

  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass http://api-gateway:4000/;
    proxy_http_version 1.1;

    proxy_set_header X-Request-Id $http_x_request_id;

    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
