apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-api-config
  namespace: asrp
data:
  OIDC_ISSUER_EXPECTED: "https://keycloak.localtest.me/realms/asrp"
  OIDC_DISCOVERY_URL: "http://keycloak.asrp.svc.cluster.local:8080/realms/asrp/.well-known/openid-configuration"
  OIDC_JWKS_URL: "http://keycloak.asrp.svc.cluster.local:8080/realms/asrp/protocol/openid-connect/certs"

  DB_HOST: "orders-db.asrp.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "orders"
  DB_USER: "asrp_orders_app"

  LOG_LEVEL: "INFO"
